/* Picori rules compiled into the PC randomizer. Keep row order stable for saved seeds. */
#ifndef PORT_RANDO_PICORI_RULES_HPP
#define PORT_RANDO_PICORI_RULES_HPP

enum NativeCondition : uint8_t {
    NATIVE_ALWAYS,
    NATIVE_START_SWORD,
    NATIVE_NO_START_SWORD,
    NATIVE_DOJO_SHUFFLED,
    NATIVE_DOJO_ORIGINAL,
    NATIVE_POOL_LEAN,
    NATIVE_POOL_NORMAL,
    NATIVE_POOL_PLENTIFUL,
    NATIVE_RUPEEMANIA,
};

struct NativeItemSpec {
    const char* name;
    RandoLogicItemType type;
    uint16_t count;
    NativeCondition when;
};

struct NativeLocationSpec {
    const char* name;
    RandoLogicLocationType type;
    uint32_t key;
    const char* requirements;
    const char* fixed_item;
    const char* tag;
    NativeCondition when;
};

static const NativeItemSpec kNativeItems[] = {
    { "Items.SmithSword", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_NO_START_SWORD },
    { "Items.GreenSword", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.RedSword", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.BlueSword", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.FourSword", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.Bombs", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.Bow", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.Boomerang", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.Shield", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.Lantern", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.GustJar", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.CaneOfPacci", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.MoleMitts", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.RocsCape", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.PegasusBoots", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.Ocarina", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.GripRing", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.PowerBracelets", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.Flippers", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.Bottle", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.Wallet", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.BombBag", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.JabberNut", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.WakeUpMushroom", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.LonLonKey", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.GraveyardKey", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.RedBook", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.GreenBook", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.BlueBook", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.EarthElement", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.FireElement", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.WaterElement", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.WindElement", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_ALWAYS },
    { "Items.SpinAttack", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_DOJO_SHUFFLED },
    { "Items.RockBreaker", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_DOJO_SHUFFLED },
    { "Items.DashAttack", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_DOJO_SHUFFLED },
    { "Items.DownThrust", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_DOJO_SHUFFLED },
    { "Items.RollAttack", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_DOJO_SHUFFLED },
    { "Items.SwordBeam", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_DOJO_SHUFFLED },
    { "Items.PerilBeam", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_DOJO_SHUFFLED },
    { "Items.GreatSpin", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_DOJO_SHUFFLED },
    { "Items.FastSpin", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_DOJO_SHUFFLED },
    { "Items.FastSplit", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_DOJO_SHUFFLED },
    { "Items.LongSpin", RANDO_LOGIC_ITEM_MAJOR, 1, NATIVE_DOJO_SHUFFLED },
    { "Items.HeartPiece", RANDO_LOGIC_ITEM_MINOR, 6, NATIVE_POOL_LEAN },
    { "Items.Rupee50", RANDO_LOGIC_ITEM_MINOR, 10, NATIVE_POOL_LEAN },
    { "Items.Shells.0x32", RANDO_LOGIC_ITEM_MINOR, 4, NATIVE_POOL_LEAN },
    { "Items.Kinstone.GreenC", RANDO_LOGIC_ITEM_MINOR, 5, NATIVE_POOL_LEAN },
    { "Items.Kinstone.RedW", RANDO_LOGIC_ITEM_MINOR, 2, NATIVE_POOL_LEAN },
    { "Items.Kinstone.BlueL", RANDO_LOGIC_ITEM_MINOR, 2, NATIVE_POOL_LEAN },
    { "Items.HeartPiece", RANDO_LOGIC_ITEM_MINOR, 30, NATIVE_POOL_PLENTIFUL },
    { "Items.HeartContainer", RANDO_LOGIC_ITEM_MINOR, 8, NATIVE_POOL_PLENTIFUL },
    { "Items.Rupee100", RANDO_LOGIC_ITEM_MINOR, 12, NATIVE_POOL_PLENTIFUL },
    { "Items.Rupee50", RANDO_LOGIC_ITEM_MINOR, 14, NATIVE_POOL_PLENTIFUL },
    { "Items.Shells.0x32", RANDO_LOGIC_ITEM_MINOR, 10, NATIVE_POOL_PLENTIFUL },
    { "Items.Kinstone.GreenC", RANDO_LOGIC_ITEM_MINOR, 10, NATIVE_POOL_PLENTIFUL },
    { "Items.Kinstone.RedW", RANDO_LOGIC_ITEM_MINOR, 5, NATIVE_POOL_PLENTIFUL },
    { "Items.Kinstone.RedV", RANDO_LOGIC_ITEM_MINOR, 5, NATIVE_POOL_PLENTIFUL },
    { "Items.Kinstone.RedE", RANDO_LOGIC_ITEM_MINOR, 5, NATIVE_POOL_PLENTIFUL },
    { "Items.Kinstone.BlueL", RANDO_LOGIC_ITEM_MINOR, 5, NATIVE_POOL_PLENTIFUL },
    { "Items.Kinstone.BlueS", RANDO_LOGIC_ITEM_MINOR, 5, NATIVE_POOL_PLENTIFUL },
    { "Items.Bombs10", RANDO_LOGIC_ITEM_MINOR, 7, NATIVE_POOL_PLENTIFUL },
    { "Items.Arrows10", RANDO_LOGIC_ITEM_MINOR, 7, NATIVE_POOL_PLENTIFUL },
    { "Items.HeartPiece", RANDO_LOGIC_ITEM_MINOR, 18, NATIVE_POOL_NORMAL },
    { "Items.HeartContainer", RANDO_LOGIC_ITEM_MINOR, 4, NATIVE_POOL_NORMAL },
    { "Items.Rupee100", RANDO_LOGIC_ITEM_MINOR, 6, NATIVE_POOL_NORMAL },
    { "Items.Rupee50", RANDO_LOGIC_ITEM_MINOR, 10, NATIVE_POOL_NORMAL },
    { "Items.Shells.0x32", RANDO_LOGIC_ITEM_MINOR, 7, NATIVE_POOL_NORMAL },
    { "Items.Kinstone.GreenC", RANDO_LOGIC_ITEM_MINOR, 7, NATIVE_POOL_NORMAL },
    { "Items.Kinstone.RedW", RANDO_LOGIC_ITEM_MINOR, 3, NATIVE_POOL_NORMAL },
    { "Items.Kinstone.RedV", RANDO_LOGIC_ITEM_MINOR, 3, NATIVE_POOL_NORMAL },
    { "Items.Kinstone.RedE", RANDO_LOGIC_ITEM_MINOR, 3, NATIVE_POOL_NORMAL },
    { "Items.Kinstone.BlueL", RANDO_LOGIC_ITEM_MINOR, 3, NATIVE_POOL_NORMAL },
    { "Items.Kinstone.BlueS", RANDO_LOGIC_ITEM_MINOR, 3, NATIVE_POOL_NORMAL },
    { "Items.Bombs10", RANDO_LOGIC_ITEM_MINOR, 4, NATIVE_POOL_NORMAL },
    { "Items.Arrows10", RANDO_LOGIC_ITEM_MINOR, 4, NATIVE_POOL_NORMAL },
    { "Items.Rupee5", RANDO_LOGIC_ITEM_FILLER, 1, NATIVE_ALWAYS },
    { "Items.Rupee20", RANDO_LOGIC_ITEM_FILLER, 1, NATIVE_ALWAYS },
    { "Items.Rupee50", RANDO_LOGIC_ITEM_FILLER, 1, NATIVE_ALWAYS },
    { "Items.Shells30", RANDO_LOGIC_ITEM_FILLER, 1, NATIVE_ALWAYS },
    { "Items.Heart", RANDO_LOGIC_ITEM_FILLER, 1, NATIVE_ALWAYS },
    { "Items.Bombs5", RANDO_LOGIC_ITEM_FILLER, 1, NATIVE_ALWAYS },
    { "Items.Arrows5", RANDO_LOGIC_ITEM_FILLER, 1, NATIVE_ALWAYS },
};

static const NativeLocationSpec kNativeLocations[] = {
    { "StartSword", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, nullptr, "Items.SmithSword", "NoSpoiler", NATIVE_START_SWORD },
    { "StartKinstoneBag", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, nullptr, "Items.KinstoneBag", "NoSpoiler", NATIVE_ALWAYS },
    { "Region_Open", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, nullptr, nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Mitts", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Bombs", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.Bombs", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Village", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.GustJar", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Castle", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.Bombs,Items.PegasusBoots", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Castor", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.PegasusBoots,Items.Bow,Items.Flippers", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Crenel", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.GripRing,Items.Bombs,Items.CaneOfPacci", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Lake", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.PegasusBoots,Items.Flippers", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Falls", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.Flippers,Items.Bombs,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Valley", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.GraveyardKey,Items.Bombs", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Clouds", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.Ocarina,Items.RocsCape,Items.FourSword", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Fortress", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.PegasusBoots,Items.Bow,Items.MoleMitts,Items.GustJar", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Deepwood", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.GustJar", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Flames", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.GripRing,Items.Bombs,Items.CaneOfPacci", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Droplets", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.Flippers,Items.Lantern,Items.GustJar", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Crypt", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.GraveyardKey,Items.Lantern", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Palace", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.Ocarina,Items.RocsCape,Items.Bow,Items.CaneOfPacci,Items.PowerBracelets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Minish", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.GustJar,Items.JabberNut", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_Fusion", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.KinstoneBag,Items.MoleMitts,Items.Flippers,Items.PegasusBoots", nullptr, nullptr, NATIVE_ALWAYS },
    { "Region_DarkCastle", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Items.FourSword,Items.EarthElement,Items.FireElement,Items.WaterElement,Items.WindElement,Items.Bow,Items.RocsCape,Items.Lantern,Items.Bombs,Items.GustJar,Items.CaneOfPacci,Items.MoleMitts,Items.PegasusBoots,Items.Flippers", nullptr, nullptr, NATIVE_ALWAYS },
    { "Goal", RANDO_LOGIC_LOCATION_HELPER, UINT32_MAX, "Helpers.Region_DarkCastle,Items.BigKey.0x1E", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_03_08_00", RANDO_LOGIC_LOCATION_ANY, 0x030800u, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_04_00_00", RANDO_LOGIC_LOCATION_ANY, 0x040000u, "Helpers.Region_Castor", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_05_05_00", RANDO_LOGIC_LOCATION_ANY, 0x050500u, "Helpers.Region_Castor", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_05_05_01", RANDO_LOGIC_LOCATION_ANY, 0x050501u, "Helpers.Region_Castor", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_07_00_00", RANDO_LOGIC_LOCATION_ANY, 0x070000u, "Helpers.Region_Castle", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_07_00_01", RANDO_LOGIC_LOCATION_ANY, 0x070001u, "Helpers.Region_Castle", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_08_01_03", RANDO_LOGIC_LOCATION_MINOR, 0x080103u, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_08_01_04", RANDO_LOGIC_LOCATION_MINOR, 0x080104u, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_08_01_05", RANDO_LOGIC_LOCATION_MINOR, 0x080105u, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_08_01_06", RANDO_LOGIC_LOCATION_MINOR, 0x080106u, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0A_00_00", RANDO_LOGIC_LOCATION_ANY, 0x0A0000u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0C_00_00", RANDO_LOGIC_LOCATION_ANY, 0x0C0000u, "Helpers.Region_Bombs,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0C_00_01", RANDO_LOGIC_LOCATION_ANY, 0x0C0001u, "Helpers.Region_Bombs,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0C_00_02", RANDO_LOGIC_LOCATION_ANY, 0x0C0002u, "Helpers.Region_Bombs,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0D_01_00", RANDO_LOGIC_LOCATION_MINOR, 0x0D0100u, "Helpers.Region_Fusion", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0D_01_01", RANDO_LOGIC_LOCATION_MINOR, 0x0D0101u, "Helpers.Region_Fusion", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0D_02_00", RANDO_LOGIC_LOCATION_MINOR, 0x0D0200u, "Helpers.Region_Fusion", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0D_03_00", RANDO_LOGIC_LOCATION_MINOR, 0x0D0300u, "Helpers.Region_Fusion", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0D_03_01", RANDO_LOGIC_LOCATION_MINOR, 0x0D0301u, "Helpers.Region_Fusion", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0D_04_00", RANDO_LOGIC_LOCATION_MINOR, 0x0D0400u, "Helpers.Region_Fusion", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0F_00_00", RANDO_LOGIC_LOCATION_ANY, 0x0F0000u, "Helpers.Region_Mitts,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0F_00_01", RANDO_LOGIC_LOCATION_ANY, 0x0F0001u, "Helpers.Region_Mitts,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_0F_00_02", RANDO_LOGIC_LOCATION_ANY, 0x0F0002u, "Helpers.Region_Mitts,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_11_02_00", RANDO_LOGIC_LOCATION_ANY, 0x110200u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_11_02_01", RANDO_LOGIC_LOCATION_ANY, 0x110201u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_11_02_02", RANDO_LOGIC_LOCATION_ANY, 0x110202u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_13_03_00", RANDO_LOGIC_LOCATION_ANY, 0x130300u, "Helpers.Region_Mitts,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_13_03_01", RANDO_LOGIC_LOCATION_ANY, 0x130301u, "Helpers.Region_Mitts,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_13_03_02", RANDO_LOGIC_LOCATION_ANY, 0x130302u, "Helpers.Region_Mitts,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_16_00_00", RANDO_LOGIC_LOCATION_ANY, 0x160000u, "Helpers.Region_Falls,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_16_00_01", RANDO_LOGIC_LOCATION_ANY, 0x160001u, "Helpers.Region_Falls,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_16_00_02", RANDO_LOGIC_LOCATION_ANY, 0x160002u, "Helpers.Region_Falls,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_17_00_00", RANDO_LOGIC_LOCATION_ANY, 0x170000u, "Helpers.Region_Castor,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_17_00_01", RANDO_LOGIC_LOCATION_ANY, 0x170001u, "Helpers.Region_Castor,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_18_00_00", RANDO_LOGIC_LOCATION_ANY, 0x180000u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_18_01_00", RANDO_LOGIC_LOCATION_ANY, 0x180100u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_18_01_01", RANDO_LOGIC_LOCATION_ANY, 0x180101u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_18_01_02", RANDO_LOGIC_LOCATION_ANY, 0x180102u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_18_02_00", RANDO_LOGIC_LOCATION_ANY, 0x180200u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_18_02_01", RANDO_LOGIC_LOCATION_ANY, 0x180201u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_18_03_00", RANDO_LOGIC_LOCATION_ANY, 0x180300u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_18_03_01", RANDO_LOGIC_LOCATION_ANY, 0x180301u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_19_00_00", RANDO_LOGIC_LOCATION_ANY, 0x190000u, "Helpers.Region_Lake,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_19_01_00", RANDO_LOGIC_LOCATION_ANY, 0x190100u, "Helpers.Region_Lake,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_19_01_01", RANDO_LOGIC_LOCATION_ANY, 0x190101u, "Helpers.Region_Lake,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_19_01_02", RANDO_LOGIC_LOCATION_ANY, 0x190102u, "Helpers.Region_Lake,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_19_01_03", RANDO_LOGIC_LOCATION_ANY, 0x190103u, "Helpers.Region_Lake,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_19_01_04", RANDO_LOGIC_LOCATION_ANY, 0x190104u, "Helpers.Region_Lake,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_19_01_05", RANDO_LOGIC_LOCATION_ANY, 0x190105u, "Helpers.Region_Lake,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_19_01_06", RANDO_LOGIC_LOCATION_ANY, 0x190106u, "Helpers.Region_Lake,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_19_01_07", RANDO_LOGIC_LOCATION_ANY, 0x190107u, "Helpers.Region_Lake,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_22_11_00", RANDO_LOGIC_LOCATION_ANY, 0x221100u, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_23_05_00", RANDO_LOGIC_LOCATION_ANY, 0x230500u, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_23_05_01", RANDO_LOGIC_LOCATION_ANY, 0x230501u, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_23_05_02", RANDO_LOGIC_LOCATION_ANY, 0x230502u, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_25_00_00", RANDO_LOGIC_LOCATION_ANY, 0x250000u, "Helpers.Region_Castle", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_25_00_01", RANDO_LOGIC_LOCATION_ANY, 0x250001u, "Helpers.Region_Castle", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_26_03_00", RANDO_LOGIC_LOCATION_ANY, 0x260300u, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_26_07_00", RANDO_LOGIC_LOCATION_ANY, 0x260700u, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_26_08_00", RANDO_LOGIC_LOCATION_ANY, 0x260800u, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_26_08_01", RANDO_LOGIC_LOCATION_ANY, 0x260801u, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_27_00_00", RANDO_LOGIC_LOCATION_ANY, 0x270000u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_27_03_00", RANDO_LOGIC_LOCATION_ANY, 0x270300u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_27_06_00", RANDO_LOGIC_LOCATION_ANY, 0x270600u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_27_07_00", RANDO_LOGIC_LOCATION_ANY, 0x270700u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_27_08_00", RANDO_LOGIC_LOCATION_ANY, 0x270800u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_27_09_00", RANDO_LOGIC_LOCATION_ANY, 0x270900u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_27_0A_00", RANDO_LOGIC_LOCATION_ANY, 0x270A00u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_27_0B_00", RANDO_LOGIC_LOCATION_ANY, 0x270B00u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_27_0C_00", RANDO_LOGIC_LOCATION_ANY, 0x270C00u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_27_0D_00", RANDO_LOGIC_LOCATION_ANY, 0x270D00u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_2A_02_00", RANDO_LOGIC_LOCATION_ANY, 0x2A0200u, "Helpers.Region_Castor", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_2E_01_00", RANDO_LOGIC_LOCATION_ANY, 0x2E0100u, "Helpers.Region_Mitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_2E_03_00", RANDO_LOGIC_LOCATION_ANY, 0x2E0300u, "Helpers.Region_Mitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_2F_01_00", RANDO_LOGIC_LOCATION_ANY, 0x2F0100u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_2F_01_01", RANDO_LOGIC_LOCATION_ANY, 0x2F0101u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_30_00_00", RANDO_LOGIC_LOCATION_ANY, 0x300000u, "Helpers.Region_Bombs", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_30_00_01", RANDO_LOGIC_LOCATION_ANY, 0x300001u, "Helpers.Region_Bombs", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_30_01_00", RANDO_LOGIC_LOCATION_ANY, 0x300100u, "Helpers.Region_Bombs", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_30_02_00", RANDO_LOGIC_LOCATION_ANY, 0x300200u, "Helpers.Region_Bombs", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_30_02_01", RANDO_LOGIC_LOCATION_ANY, 0x300201u, "Helpers.Region_Bombs", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_30_02_02", RANDO_LOGIC_LOCATION_ANY, 0x300202u, "Helpers.Region_Bombs", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_30_03_00", RANDO_LOGIC_LOCATION_ANY, 0x300300u, "Helpers.Region_Bombs", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_30_03_01", RANDO_LOGIC_LOCATION_ANY, 0x300301u, "Helpers.Region_Bombs", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_32_00_00", RANDO_LOGIC_LOCATION_ANY, 0x320000u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_32_00_01", RANDO_LOGIC_LOCATION_ANY, 0x320001u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_32_00_02", RANDO_LOGIC_LOCATION_ANY, 0x320002u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_32_00_03", RANDO_LOGIC_LOCATION_ANY, 0x320003u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_32_00_04", RANDO_LOGIC_LOCATION_ANY, 0x320004u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_32_07_00", RANDO_LOGIC_LOCATION_ANY, 0x320700u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_32_0B_00", RANDO_LOGIC_LOCATION_ANY, 0x320B00u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_32_0C_00", RANDO_LOGIC_LOCATION_ANY, 0x320C00u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_32_0D_00", RANDO_LOGIC_LOCATION_ANY, 0x320D00u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_32_0F_00", RANDO_LOGIC_LOCATION_ANY, 0x320F00u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_32_13_00", RANDO_LOGIC_LOCATION_ANY, 0x321300u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_33_00_00", RANDO_LOGIC_LOCATION_ANY, 0x330000u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_33_02_00", RANDO_LOGIC_LOCATION_ANY, 0x330200u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_33_05_00", RANDO_LOGIC_LOCATION_ANY, 0x330500u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_34_01_00", RANDO_LOGIC_LOCATION_ANY, 0x340100u, "Helpers.Region_Valley", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_35_00_00", RANDO_LOGIC_LOCATION_ANY, 0x350000u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_35_01_00", RANDO_LOGIC_LOCATION_ANY, 0x350100u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_35_03_00", RANDO_LOGIC_LOCATION_ANY, 0x350300u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_35_05_00", RANDO_LOGIC_LOCATION_ANY, 0x350500u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_35_07_00", RANDO_LOGIC_LOCATION_ANY, 0x350700u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_35_09_00", RANDO_LOGIC_LOCATION_ANY, 0x350900u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_35_09_01", RANDO_LOGIC_LOCATION_ANY, 0x350901u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_35_09_02", RANDO_LOGIC_LOCATION_ANY, 0x350902u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_36_00_00", RANDO_LOGIC_LOCATION_ANY, 0x360000u, "Helpers.Region_Castle", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_36_01_00", RANDO_LOGIC_LOCATION_ANY, 0x360100u, "Helpers.Region_Castle", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_37_00_00", RANDO_LOGIC_LOCATION_ANY, 0x370000u, "Helpers.Region_Castle", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_37_01_00", RANDO_LOGIC_LOCATION_ANY, 0x370100u, "Helpers.Region_Castle", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_41_00_00", RANDO_LOGIC_LOCATION_ANY, 0x410000u, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_41_00_01", RANDO_LOGIC_LOCATION_ANY, 0x410001u, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_41_00_02", RANDO_LOGIC_LOCATION_ANY, 0x410002u, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_41_00_03", RANDO_LOGIC_LOCATION_ANY, 0x410003u, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_41_00_04", RANDO_LOGIC_LOCATION_ANY, 0x410004u, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_48_00_00", RANDO_LOGIC_LOCATION_ANY, 0x480000u, "Helpers.Region_Deepwood", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_48_01_00", RANDO_LOGIC_LOCATION_ANY, 0x480100u, "Helpers.Region_Deepwood", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_48_01_01", RANDO_LOGIC_LOCATION_ANY, 0x480101u, "Helpers.Region_Deepwood", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_48_02_00", RANDO_LOGIC_LOCATION_ANY, 0x480200u, "Helpers.Region_Deepwood", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_48_04_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x480400u, "Helpers.Region_Deepwood", "Items.SmallKey.0x18", nullptr, NATIVE_ALWAYS },
    { "Chest_48_05_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x480500u, "Helpers.Region_Deepwood", "Items.DungeonMap.0x18", nullptr, NATIVE_ALWAYS },
    { "Chest_48_06_00", RANDO_LOGIC_LOCATION_ANY, 0x480600u, "Helpers.Region_Deepwood", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_48_10_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x481000u, "Helpers.Region_Deepwood", "Items.SmallKey.0x18", nullptr, NATIVE_ALWAYS },
    { "Chest_48_11_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x481100u, "Helpers.Region_Deepwood", "Items.BigKey.0x18", nullptr, NATIVE_ALWAYS },
    { "Chest_48_12_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x481200u, "Helpers.Region_Deepwood", "Items.SmallKey.0x18", nullptr, NATIVE_ALWAYS },
    { "Chest_48_12_01", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x481201u, "Helpers.Region_Deepwood", "Items.Compass.0x18", nullptr, NATIVE_ALWAYS },
    { "Chest_48_17_00", RANDO_LOGIC_LOCATION_ANY, 0x481700u, "Helpers.Region_Deepwood", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_50_01_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x500100u, "Helpers.Region_Flames", "Items.SmallKey.0x19", nullptr, NATIVE_ALWAYS },
    { "Chest_50_01_01", RANDO_LOGIC_LOCATION_ANY, 0x500101u, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_50_08_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x500800u, "Helpers.Region_Flames", "Items.SmallKey.0x19", nullptr, NATIVE_ALWAYS },
    { "Chest_50_08_01", RANDO_LOGIC_LOCATION_ANY, 0x500801u, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_50_09_00", RANDO_LOGIC_LOCATION_ANY, 0x500900u, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_50_09_01", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x500901u, "Helpers.Region_Flames", "Items.DungeonMap.0x19", nullptr, NATIVE_ALWAYS },
    { "Chest_50_10_00", RANDO_LOGIC_LOCATION_ANY, 0x501000u, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_50_10_01", RANDO_LOGIC_LOCATION_ANY, 0x501001u, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_50_14_00", RANDO_LOGIC_LOCATION_ANY, 0x501400u, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_50_15_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x501500u, "Helpers.Region_Flames", "Items.Compass.0x19", nullptr, NATIVE_ALWAYS },
    { "Chest_50_17_00", RANDO_LOGIC_LOCATION_ANY, 0x501700u, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_50_17_01", RANDO_LOGIC_LOCATION_ANY, 0x501701u, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_50_17_02", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x501702u, "Helpers.Region_Flames", "Items.BigKey.0x19", nullptr, NATIVE_ALWAYS },
    { "Chest_58_00_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x580000u, "Helpers.Region_Fortress", "Items.Compass.0x1A", nullptr, NATIVE_ALWAYS },
    { "Chest_58_05_00", RANDO_LOGIC_LOCATION_ANY, 0x580500u, "Helpers.Region_Fortress", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_58_05_01", RANDO_LOGIC_LOCATION_ANY, 0x580501u, "Helpers.Region_Fortress", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_58_19_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x581900u, "Helpers.Region_Fortress", "Items.DungeonMap.0x1A", nullptr, NATIVE_ALWAYS },
    { "Chest_58_1B_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x581B00u, "Helpers.Region_Fortress", "Items.BigKey.0x1A", nullptr, NATIVE_ALWAYS },
    { "Chest_58_1D_00", RANDO_LOGIC_LOCATION_ANY, 0x581D00u, "Helpers.Region_Fortress", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_58_1D_01", RANDO_LOGIC_LOCATION_ANY, 0x581D01u, "Helpers.Region_Fortress", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_58_23_00", RANDO_LOGIC_LOCATION_ANY, 0x582300u, "Helpers.Region_Fortress", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_60_09_00", RANDO_LOGIC_LOCATION_ANY, 0x600900u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_60_0A_00", RANDO_LOGIC_LOCATION_ANY, 0x600A00u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_60_0D_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x600D00u, "Helpers.Region_Droplets", "Items.DungeonMap.0x1B", nullptr, NATIVE_ALWAYS },
    { "Chest_60_10_00", RANDO_LOGIC_LOCATION_ANY, 0x601000u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_60_11_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x601100u, "Helpers.Region_Droplets", "Items.SmallKey.0x1B", nullptr, NATIVE_ALWAYS },
    { "Chest_60_28_00", RANDO_LOGIC_LOCATION_ANY, 0x602800u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_60_28_01", RANDO_LOGIC_LOCATION_ANY, 0x602801u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_60_2B_00", RANDO_LOGIC_LOCATION_ANY, 0x602B00u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_60_2B_01", RANDO_LOGIC_LOCATION_ANY, 0x602B01u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_60_2B_02", RANDO_LOGIC_LOCATION_ANY, 0x602B02u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_60_2D_00", RANDO_LOGIC_LOCATION_ANY, 0x602D00u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_60_32_00", RANDO_LOGIC_LOCATION_ANY, 0x603200u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_60_32_01", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x603201u, "Helpers.Region_Droplets", "Items.Compass.0x1B", nullptr, NATIVE_ALWAYS },
    { "Chest_62_01_00", RANDO_LOGIC_LOCATION_ANY, 0x620100u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_62_03_00", RANDO_LOGIC_LOCATION_ANY, 0x620300u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_62_04_00", RANDO_LOGIC_LOCATION_ANY, 0x620400u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_62_10_00", RANDO_LOGIC_LOCATION_ANY, 0x621000u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_62_12_00", RANDO_LOGIC_LOCATION_ANY, 0x621200u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_68_05_00", RANDO_LOGIC_LOCATION_ANY, 0x680500u, "Helpers.Region_Crypt", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_70_01_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x700100u, "Helpers.Region_Palace", "Items.BigKey.0x1D", nullptr, NATIVE_ALWAYS },
    { "Chest_70_03_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x700300u, "Helpers.Region_Palace", "Items.SmallKey.0x1D", nullptr, NATIVE_ALWAYS },
    { "Chest_70_04_00", RANDO_LOGIC_LOCATION_MINOR, 0x700400u, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_70_07_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x700700u, "Helpers.Region_Palace", "Items.SmallKey.0x1D", nullptr, NATIVE_ALWAYS },
    { "Chest_70_0F_00", RANDO_LOGIC_LOCATION_MINOR, 0x700F00u, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_70_10_00", RANDO_LOGIC_LOCATION_MINOR, 0x701000u, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_70_15_00", RANDO_LOGIC_LOCATION_MINOR, 0x701500u, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_70_1C_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x701C00u, "Helpers.Region_Palace", "Items.DungeonMap.0x1D", nullptr, NATIVE_ALWAYS },
    { "Chest_70_29_00", RANDO_LOGIC_LOCATION_MINOR, 0x702900u, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_70_2B_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x702B00u, "Helpers.Region_Palace", "Items.SmallKey.0x1D", nullptr, NATIVE_ALWAYS },
    { "Chest_70_2C_00", RANDO_LOGIC_LOCATION_MINOR, 0x702C00u, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_70_2D_00", RANDO_LOGIC_LOCATION_MINOR, 0x702D00u, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_ALWAYS },
    { "Chest_70_32_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x703200u, "Helpers.Region_Palace", "Items.Compass.0x1D", nullptr, NATIVE_ALWAYS },
    { "Chest_70_32_01", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x703201u, "Helpers.Region_Palace", "Items.SmallKey.0x1D", nullptr, NATIVE_ALWAYS },
    { "Chest_88_01_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x880100u, "Helpers.Region_DarkCastle", "Items.SmallKey.0x1E", nullptr, NATIVE_ALWAYS },
    { "Chest_88_02_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x880200u, "Helpers.Region_DarkCastle", "Items.SmallKey.0x1E", nullptr, NATIVE_ALWAYS },
    { "Chest_88_03_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x880300u, "Helpers.Region_DarkCastle", "Items.SmallKey.0x1E", nullptr, NATIVE_ALWAYS },
    { "Chest_88_04_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x880400u, "Helpers.Region_DarkCastle", "Items.SmallKey.0x1E", nullptr, NATIVE_ALWAYS },
    { "Chest_88_09_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x880900u, "Helpers.Region_DarkCastle", "Items.BigKey.0x1E", nullptr, NATIVE_ALWAYS },
    { "Chest_88_20_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x882000u, "Helpers.Region_DarkCastle", "Items.Compass.0x1E", nullptr, NATIVE_ALWAYS },
    { "Chest_88_27_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x882700u, "Helpers.Region_DarkCastle", "Items.SmallKey.0x1E", nullptr, NATIVE_ALWAYS },
    { "Chest_88_37_00", RANDO_LOGIC_LOCATION_UNSHUFFLED, 0x883700u, "Helpers.Region_DarkCastle", "Items.DungeonMap.0x1E", nullptr, NATIVE_ALWAYS },
    { "Droplets_Entrance_B2_WestIceblock", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, "Helpers.Region_Droplets", "Items.BigKey.0x1B", nullptr, NATIVE_ALWAYS },
    { "Ground_00_00_3C", RANDO_LOGIC_LOCATION_ANY, 0x00003Cu, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_00_00_3D", RANDO_LOGIC_LOCATION_ANY, 0x00003Du, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_01_01_C2", RANDO_LOGIC_LOCATION_ANY, 0x0101C2u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_03_05_7E", RANDO_LOGIC_LOCATION_ANY, 0x03057Eu, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_03_05_7F", RANDO_LOGIC_LOCATION_ANY, 0x03057Fu, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_03_06_8F", RANDO_LOGIC_LOCATION_ANY, 0x03068Fu, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_06_04_4B", RANDO_LOGIC_LOCATION_ANY, 0x06044Bu, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_08_01_E5", RANDO_LOGIC_LOCATION_MINOR, 0x0801E5u, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_08_01_E6", RANDO_LOGIC_LOCATION_MINOR, 0x0801E6u, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_08_01_E7", RANDO_LOGIC_LOCATION_MINOR, 0x0801E7u, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_08_01_E8", RANDO_LOGIC_LOCATION_MINOR, 0x0801E8u, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_08_01_E9", RANDO_LOGIC_LOCATION_MINOR, 0x0801E9u, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_08_01_EA", RANDO_LOGIC_LOCATION_MINOR, 0x0801EAu, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_08_01_EB", RANDO_LOGIC_LOCATION_MINOR, 0x0801EBu, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_0A_00_A1", RANDO_LOGIC_LOCATION_ANY, 0x0A00A1u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_0A_00_A3", RANDO_LOGIC_LOCATION_ANY, 0x0A00A3u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_0A_00_A4", RANDO_LOGIC_LOCATION_ANY, 0x0A00A4u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_0A_00_A5", RANDO_LOGIC_LOCATION_ANY, 0x0A00A5u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_0A_00_A8", RANDO_LOGIC_LOCATION_ANY, 0x0A00A8u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_0A_00_AA", RANDO_LOGIC_LOCATION_ANY, 0x0A00AAu, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_0A_00_AB", RANDO_LOGIC_LOCATION_ANY, 0x0A00ABu, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_0B_00_08", RANDO_LOGIC_LOCATION_ANY, 0x0B0008u, "Helpers.Region_Lake", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_0B_00_0A", RANDO_LOGIC_LOCATION_ANY, 0x0B000Au, "Helpers.Region_Lake", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_10_00_BA", RANDO_LOGIC_LOCATION_ANY, 0x1000BAu, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_10_00_BC", RANDO_LOGIC_LOCATION_ANY, 0x1000BCu, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_10_00_BD", RANDO_LOGIC_LOCATION_ANY, 0x1000BDu, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_10_00_BF", RANDO_LOGIC_LOCATION_ANY, 0x1000BFu, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_11_02_7E", RANDO_LOGIC_LOCATION_ANY, 0x11027Eu, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_11_03_BA", RANDO_LOGIC_LOCATION_ANY, 0x1103BAu, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_13_00_46", RANDO_LOGIC_LOCATION_ANY, 0x130046u, "Helpers.Region_Mitts,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_14_00_45", RANDO_LOGIC_LOCATION_ANY, 0x140045u, "Helpers.Region_Crenel,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_18_00_4E", RANDO_LOGIC_LOCATION_ANY, 0x18004Eu, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_18_01_59", RANDO_LOGIC_LOCATION_ANY, 0x180159u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_18_01_5A", RANDO_LOGIC_LOCATION_ANY, 0x18015Au, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_21_0A_B8", RANDO_LOGIC_LOCATION_ANY, 0x210AB8u, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_23_05_B4", RANDO_LOGIC_LOCATION_ANY, 0x2305B4u, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_25_00_80", RANDO_LOGIC_LOCATION_ANY, 0x250080u, "Helpers.Region_Castle", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_25_04_7F", RANDO_LOGIC_LOCATION_ANY, 0x25047Fu, "Helpers.Region_Castle", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_25_05_83", RANDO_LOGIC_LOCATION_ANY, 0x250583u, "Helpers.Region_Castle", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_25_06_82", RANDO_LOGIC_LOCATION_ANY, 0x250682u, "Helpers.Region_Castle", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_26_05_7D", RANDO_LOGIC_LOCATION_ANY, 0x26057Du, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_26_08_40", RANDO_LOGIC_LOCATION_ANY, 0x260840u, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_26_09_43", RANDO_LOGIC_LOCATION_ANY, 0x260943u, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_26_09_44", RANDO_LOGIC_LOCATION_ANY, 0x260944u, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_26_09_45", RANDO_LOGIC_LOCATION_ANY, 0x260945u, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_2A_04_38", RANDO_LOGIC_LOCATION_ANY, 0x2A0438u, "Helpers.Region_Castor", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_32_15_7B", RANDO_LOGIC_LOCATION_ANY, 0x32157Bu, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_33_08_4F", RANDO_LOGIC_LOCATION_ANY, 0x33084Fu, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_33_08_58", RANDO_LOGIC_LOCATION_ANY, 0x330858u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_33_08_59", RANDO_LOGIC_LOCATION_ANY, 0x330859u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_33_08_5A", RANDO_LOGIC_LOCATION_ANY, 0x33085Au, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_33_08_5B", RANDO_LOGIC_LOCATION_ANY, 0x33085Bu, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_34_00_5D", RANDO_LOGIC_LOCATION_ANY, 0x34005Du, "Helpers.Region_Valley", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_35_03_7E", RANDO_LOGIC_LOCATION_ANY, 0x35037Eu, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_35_04_81", RANDO_LOGIC_LOCATION_ANY, 0x350481u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_35_09_7A", RANDO_LOGIC_LOCATION_ANY, 0x35097Au, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_48_01_4F", RANDO_LOGIC_LOCATION_ANY, 0x48014Fu, "Helpers.Region_Deepwood", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_48_05_52", RANDO_LOGIC_LOCATION_ANY, 0x480552u, "Helpers.Region_Deepwood", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_50_06_3C", RANDO_LOGIC_LOCATION_ANY, 0x50063Cu, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_58_24_47", RANDO_LOGIC_LOCATION_ANY, 0x582447u, "Helpers.Region_Fortress", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_60_06_95", RANDO_LOGIC_LOCATION_ANY, 0x600695u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_60_06_96", RANDO_LOGIC_LOCATION_ANY, 0x600696u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_60_06_97", RANDO_LOGIC_LOCATION_ANY, 0x600697u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_60_06_98", RANDO_LOGIC_LOCATION_ANY, 0x600698u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_62_00_C3", RANDO_LOGIC_LOCATION_ANY, 0x6200C3u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_62_10_13", RANDO_LOGIC_LOCATION_ANY, 0x621013u, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_70_0F_80", RANDO_LOGIC_LOCATION_MINOR, 0x700F80u, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_ALWAYS },
    { "Ground_18_01_55", RANDO_LOGIC_LOCATION_ANY, 0x180155u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_18_01_56", RANDO_LOGIC_LOCATION_ANY, 0x180156u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_18_01_57", RANDO_LOGIC_LOCATION_ANY, 0x180157u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_18_01_58", RANDO_LOGIC_LOCATION_ANY, 0x180158u, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_18_01_5B", RANDO_LOGIC_LOCATION_ANY, 0x18015Bu, "Helpers.Region_Fortress,Items.MoleMitts", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_33_08_4D", RANDO_LOGIC_LOCATION_ANY, 0x33084Du, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_33_08_4E", RANDO_LOGIC_LOCATION_ANY, 0x33084Eu, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_33_08_50", RANDO_LOGIC_LOCATION_ANY, 0x330850u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_33_08_51", RANDO_LOGIC_LOCATION_ANY, 0x330851u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_33_08_52", RANDO_LOGIC_LOCATION_ANY, 0x330852u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_33_08_53", RANDO_LOGIC_LOCATION_ANY, 0x330853u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_33_08_54", RANDO_LOGIC_LOCATION_ANY, 0x330854u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_33_08_55", RANDO_LOGIC_LOCATION_ANY, 0x330855u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_33_08_56", RANDO_LOGIC_LOCATION_ANY, 0x330856u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_33_08_57", RANDO_LOGIC_LOCATION_ANY, 0x330857u, "Helpers.Region_Falls", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_50_05_3E", RANDO_LOGIC_LOCATION_ANY, 0x50053Eu, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_50_05_3F", RANDO_LOGIC_LOCATION_ANY, 0x50053Fu, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_50_05_40", RANDO_LOGIC_LOCATION_ANY, 0x500540u, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_50_05_41", RANDO_LOGIC_LOCATION_ANY, 0x500541u, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_50_05_42", RANDO_LOGIC_LOCATION_ANY, 0x500542u, "Helpers.Region_Flames", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_06_99", RANDO_LOGIC_LOCATION_ANY, 0x600699u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_06_9A", RANDO_LOGIC_LOCATION_ANY, 0x60069Au, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_0D_85", RANDO_LOGIC_LOCATION_ANY, 0x600D85u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_0D_86", RANDO_LOGIC_LOCATION_ANY, 0x600D86u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_0D_87", RANDO_LOGIC_LOCATION_ANY, 0x600D87u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_0D_88", RANDO_LOGIC_LOCATION_ANY, 0x600D88u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_0D_89", RANDO_LOGIC_LOCATION_ANY, 0x600D89u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_25_8A", RANDO_LOGIC_LOCATION_ANY, 0x60258Au, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_25_8B", RANDO_LOGIC_LOCATION_ANY, 0x60258Bu, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_25_8C", RANDO_LOGIC_LOCATION_ANY, 0x60258Cu, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_25_8D", RANDO_LOGIC_LOCATION_ANY, 0x60258Du, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_25_8E", RANDO_LOGIC_LOCATION_ANY, 0x60258Eu, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_31_8F", RANDO_LOGIC_LOCATION_ANY, 0x60318Fu, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_31_90", RANDO_LOGIC_LOCATION_ANY, 0x603190u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_31_91", RANDO_LOGIC_LOCATION_ANY, 0x603191u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_31_92", RANDO_LOGIC_LOCATION_ANY, 0x603192u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_31_93", RANDO_LOGIC_LOCATION_ANY, 0x603193u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_60_31_94", RANDO_LOGIC_LOCATION_ANY, 0x603194u, "Helpers.Region_Droplets", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_70_21_5A", RANDO_LOGIC_LOCATION_MINOR, 0x70215Au, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_70_21_5B", RANDO_LOGIC_LOCATION_MINOR, 0x70215Bu, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_70_21_5C", RANDO_LOGIC_LOCATION_MINOR, 0x70215Cu, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_70_21_5D", RANDO_LOGIC_LOCATION_MINOR, 0x70215Du, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Ground_70_21_5E", RANDO_LOGIC_LOCATION_MINOR, 0x70215Eu, "Helpers.Region_Palace", nullptr, nullptr, NATIVE_RUPEEMANIA },
    { "Smith_Floor_Item1", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Smith_Floor_Item2", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Town_Shop_80Item", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Town_Shop_300Item", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.Wallet", nullptr, nullptr, NATIVE_ALWAYS },
    { "Town_Dojo_NPC1", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.SmithSword", nullptr, nullptr, NATIVE_DOJO_SHUFFLED },
    { "Town_Dojo_NPC1", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, "Items.SmithSword", "Items.SpinAttack", nullptr, NATIVE_DOJO_ORIGINAL },
    { "Town_Dojo_NPC2", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.FourSword,Items.SpinAttack", nullptr, nullptr, NATIVE_DOJO_SHUFFLED },
    { "Town_Dojo_NPC2", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, "Items.FourSword,Items.SpinAttack", "Items.RockBreaker", nullptr, NATIVE_DOJO_ORIGINAL },
    { "Town_Dojo_NPC3", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.FourSword,Items.SpinAttack", nullptr, nullptr, NATIVE_DOJO_SHUFFLED },
    { "Town_Dojo_NPC3", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, "Items.FourSword,Items.SpinAttack", "Items.DashAttack", nullptr, NATIVE_DOJO_ORIGINAL },
    { "Town_Dojo_NPC4", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.FourSword,Items.SpinAttack", nullptr, nullptr, NATIVE_DOJO_SHUFFLED },
    { "Town_Dojo_NPC4", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, "Items.FourSword,Items.SpinAttack", "Items.DownThrust", nullptr, NATIVE_DOJO_ORIGINAL },
    { "Crenel_Dojo_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.FourSword,Items.SpinAttack", nullptr, nullptr, NATIVE_DOJO_SHUFFLED },
    { "Crenel_Dojo_NPC", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, "Items.FourSword,Items.SpinAttack", "Items.RollAttack", nullptr, NATIVE_DOJO_ORIGINAL },
    { "Castle_Dojo_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.FourSword,Items.SpinAttack", nullptr, nullptr, NATIVE_DOJO_SHUFFLED },
    { "Castle_Dojo_NPC", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, "Items.FourSword,Items.SpinAttack", "Items.SwordBeam", nullptr, NATIVE_DOJO_ORIGINAL },
    { "Hylia_Dojo_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.FourSword,Items.SpinAttack", nullptr, nullptr, NATIVE_DOJO_SHUFFLED },
    { "Hylia_Dojo_NPC", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, "Items.FourSword,Items.SpinAttack", "Items.PerilBeam", nullptr, NATIVE_DOJO_ORIGINAL },
    { "Swamp_Dojo_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.FourSword,Items.SpinAttack", nullptr, nullptr, NATIVE_DOJO_SHUFFLED },
    { "Swamp_Dojo_NPC", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, "Items.FourSword,Items.SpinAttack", "Items.GreatSpin", nullptr, NATIVE_DOJO_ORIGINAL },
    { "Swamp_WaterfallFusion_DojoNPC", RANDO_LOGIC_LOCATION_MINOR, UINT32_MAX, "Items.FourSword,Items.SpinAttack", nullptr, nullptr, NATIVE_DOJO_SHUFFLED },
    { "Swamp_WaterfallFusion_DojoNPC", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, "Items.FourSword,Items.SpinAttack", "Items.FastSpin", nullptr, NATIVE_DOJO_ORIGINAL },
    { "FallsLower_WaterfallFusion_DojoNPC", RANDO_LOGIC_LOCATION_MINOR, UINT32_MAX, "Items.FourSword,Items.SpinAttack", nullptr, nullptr, NATIVE_DOJO_SHUFFLED },
    { "FallsLower_WaterfallFusion_DojoNPC", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, "Items.FourSword,Items.SpinAttack", "Items.FastSplit", nullptr, NATIVE_DOJO_ORIGINAL },
    { "NorthField_WaterfallFusion_DojoNPC", RANDO_LOGIC_LOCATION_MINOR, UINT32_MAX, "Items.FourSword,Items.SpinAttack", nullptr, nullptr, NATIVE_DOJO_SHUFFLED },
    { "NorthField_WaterfallFusion_DojoNPC", RANDO_LOGIC_LOCATION_UNSHUFFLED, UINT32_MAX, "Items.FourSword,Items.SpinAttack", "Items.LongSpin", nullptr, NATIVE_DOJO_ORIGINAL },
    { "Town_Cuccos_Lv_10_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.PegasusBoots", nullptr, nullptr, NATIVE_ALWAYS },
    { "Hylia_DogNPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Lake", nullptr, nullptr, NATIVE_ALWAYS },
    { "MinishVillage_BarrelHouse_Item", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Village", nullptr, nullptr, NATIVE_ALWAYS },
    { "Town_Jullieta_Item", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.PegasusBoots,Items.Flippers", nullptr, nullptr, NATIVE_ALWAYS },
    { "Town_DrLeft_AtticItem", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.PegasusBoots,Items.Flippers,Items.GustJar", nullptr, nullptr, NATIVE_ALWAYS },
    { "Hylia_MayorCabin_Item", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Lake,Items.GustJar", nullptr, nullptr, NATIVE_ALWAYS },
    { "Crenel_Melari_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Town_ShoeShop_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.WakeUpMushroom", nullptr, nullptr, NATIVE_ALWAYS },
    { "MinishWoods_BombMinish_NPC1", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.JabberNut,Items.GustJar", nullptr, nullptr, NATIVE_ALWAYS },
    { "MinishWoods_BombMinish_NPC2", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.JabberNut,Items.GustJar", nullptr, nullptr, NATIVE_ALWAYS },
    { "Minish_GreatFairy_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Minish,Items.Bombs", nullptr, nullptr, NATIVE_ALWAYS },
    { "Crenel_GreatFairy_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Valley_GreatFairy_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Valley", nullptr, nullptr, NATIVE_ALWAYS },
    { "Valley_DampeNPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Valley", nullptr, nullptr, NATIVE_ALWAYS },
    { "MinishWoods_WitchHut_Item", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Open", nullptr, nullptr, NATIVE_ALWAYS },
    { "Falls_Biggoron", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Falls,Items.Shield", nullptr, nullptr, NATIVE_ALWAYS },
    { "Town_Library_YellowMinish_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.JabberNut,Items.PegasusBoots,Items.Flippers", nullptr, nullptr, NATIVE_ALWAYS },
    { "Deepwood_Prize", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Deepwood,Items.BigKey.0x18", nullptr, nullptr, NATIVE_ALWAYS },
    { "CoF_Prize", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Flames,Items.BigKey.0x19", nullptr, nullptr, NATIVE_ALWAYS },
    { "Droplets_Prize", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Droplets,Items.BigKey.0x1B", nullptr, nullptr, NATIVE_ALWAYS },
    { "Palace_Prize", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Palace,Items.BigKey.0x1D", nullptr, nullptr, NATIVE_ALWAYS },
    { "Town_CafeLady_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.PegasusBoots", nullptr, nullptr, NATIVE_ALWAYS },
    { "Crypt_Prize", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Crypt", nullptr, nullptr, NATIVE_ALWAYS },
    { "WindTribe_2F_Gregal_NPC1", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "WindTribe_2F_Gregal_NPC2", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Clouds", nullptr, nullptr, NATIVE_ALWAYS },
    { "Trilby_Scrub_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.Bombs", nullptr, nullptr, NATIVE_ALWAYS },
    { "Crenel_Scrub_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Crenel", nullptr, nullptr, NATIVE_ALWAYS },
    { "Fortress_Prize", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Helpers.Region_Fortress,Items.BigKey.0x1A", nullptr, nullptr, NATIVE_ALWAYS },
    { "Town_Bell_HP", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.RocsCape", nullptr, nullptr, NATIVE_ALWAYS },
    { "SouthField_Tingle_NPC", RANDO_LOGIC_LOCATION_ANY, UINT32_MAX, "Items.FourSword", nullptr, nullptr, NATIVE_ALWAYS },
};

#endif /* PORT_RANDO_PICORI_RULES_HPP */
