"""Build a voxel Link from his own sprites, by visual hull.

WHY THIS IS A SEPARATE TOOL
    Every other fitter in this project works from ONE view, because a room
    tile only ever has one. That is why so much of shapefit.py is careful
    inference: a rock's depth has to be argued for from its shading, and a
    tree's from its outline, because nothing in the drawing states it.

    Link is different and much easier. He is drawn from four sides --
    south, north, east, west -- and four orthogonal silhouettes determine
    a solid directly. No inference, no declared heights: intersect the
    extrusions and what survives is the shape. This is the one asset in
    the game where we can stop guessing.

GETTING THE SPRITES
    They are not in the decomp. Link's art and even his OAM frame lists
    (gFrameObjLists.s, gSpriteAnimations_*.s) are generated by the ROM
    extraction step, so a fresh checkout has neither until the ROM is
    supplied. Harvest them from a build, then point this tool at the PNGs:

        TMC_SPRITEDUMP=1 xmake run tmc_pc
        python3 tools/fit_link.py dump/ link.obj

    Nothing from the ROM is kept: the PNGs are a local cache, the .obj is
    derived geometry, and both stay out of the distribution.

A WARNING FROM LAST TIME
    An earlier sweep harvested 16,895 frames and none of them were usable,
    because a dumped frame is an OAM COMPOSITE -- Link plus whatever he is
    holding plus any effect playing over him. Bounding boxes came out in
    multiples of 8 (OAM tile granularity) and his body could not be
    separated from his sword. So: harvest an IDLE frame per direction, and
    this tool checks that the four views agree before it builds anything.
"""
import sys
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
import viewangle as VA           # noqa: E402

# From the decomp, src/playerHitbox.c:
#   const Hitbox gPlayerHitbox = { 0, -3, { 5, 3, 3, 5 }, 6, 6 };
# a 6x6 ground footprint. That is the one hard number about Link's size
# that does not come from the ROM, so it is what the model is scaled to.
HITBOX_W = 6
HITBOX_D = 6

DIRS = ("south", "north", "east", "west")


def silhouette(path, tol=12):
    """Opaque (or non-background) pixels of a sprite frame."""
    im = Image.open(path).convert("RGBA")
    a = np.array(im)
    if a[:, :, 3].max() > 0 and a[:, :, 3].min() == 0:
        m = a[:, :, 3] > 8
    else:
        bg = a[0, 0, :3].astype(int)
        m = np.abs(a[:, :, :3].astype(int) - bg).sum(2) > tol
    ys, xs = np.where(m)
    if not len(ys):
        raise ValueError(f"{path}: empty sprite")
    return m[ys.min():ys.max() + 1, xs.min():xs.max() + 1], a


def visual_hull(front, side):
    """Intersect a front and a side silhouette into a solid.

    front[y, x] is what you see looking north; side[y, z] looking west.
    A voxel (x, y, z) is solid when BOTH views show something there, which
    is the standard shape-from-silhouette carve. With only two axes this
    cannot hollow out a concavity -- it gives the convex-in-plan hull --
    but for a humanoid read at this size that is the right answer and it
    is honest about what two views can determine.
    """
    h = min(front.shape[0], side.shape[0])
    front = front[-h:, :]
    side = side[-h:, :]
    w = front.shape[1]
    d = side.shape[1]
    vox = set()
    for y in range(h):
        fx = np.where(front[y])[0]
        sz = np.where(side[y])[0]
        if not len(fx) or not len(sz):
            continue
        for x in fx:
            for z in sz:
                vox.add((int(x), int(h - 1 - y), int(z)))
    return vox, w, h, d


def check_views(masks):
    """The four views must agree on his height, and the pairs on width."""
    hs = {k: m.shape[0] for k, m in masks.items()}
    spread = max(hs.values()) - min(hs.values())
    notes = [f"  heights {hs}"]
    ok = spread <= 2
    if not ok:
        notes.append(f"  REFUSING: views disagree on height by {spread}px. "
                     "That is the OAM-composite problem -- a held item or an "
                     "effect is in at least one frame. Harvest idle frames.")
    fw, bw = masks["south"].shape[1], masks["north"].shape[1]
    ew, ww = masks["east"].shape[1], masks["west"].shape[1]
    notes.append(f"  front/back width {fw}/{bw}, side depth {ew}/{ww}")
    if abs(fw - bw) > 2 or abs(ew - ww) > 2:
        notes.append("  WARNING: opposing views differ in width; using the "
                     "narrower of each pair.")
    return ok, notes


def build(dumpdir, out):
    d = Path(dumpdir)
    masks = {}
    for k in DIRS:
        hits = sorted(d.glob(f"*{k}*.png"))
        if not hits:
            sys.exit(f"no {k}-facing frame in {d} (looked for *{k}*.png)")
        masks[k], _ = silhouette(hits[0])
        print(f"  {k:<6} {hits[0].name}  {masks[k].shape[1]}x"
              f"{masks[k].shape[0]}")
    ok, notes = check_views(masks)
    for n in notes:
        print(n)
    if not ok:
        sys.exit(1)

    front = masks["south"] if masks["south"].shape[1] <= masks["north"].shape[1] \
        else masks["north"]
    side = masks["east"] if masks["east"].shape[1] <= masks["west"].shape[1] \
        else masks["west"]
    vox, w, h, dep = visual_hull(front, side)

    drawn = h
    height, depth = VA.split_drawn(drawn, depth=dep)
    print(f"  visual hull: {len(vox)} voxels, {w} wide x {dep} deep x "
          f"{h} drawn")
    print(f"  camera says drawn {drawn} = height {height} + depth {depth} "
          f"({VA.OBLIQUE_DEG:.0f} deg oblique)")
    print(f"  hitbox says his ground footprint is {HITBOX_W}x{HITBOX_D}; "
          f"sprite plan is {w}x{dep}, so 1 hitbox unit ~ "
          f"{w / float(HITBOX_W):.2f}px")
    Path(out).write_text(_obj(vox))
    print(f"  -> {out}")


def _obj(vox):
    lines = ["# Link, visual hull from four sprite views.",
             "# +Z is SOUTH (toward the camera)."]
    idx = {}
    verts = []
    faces = []
    for (x, y, z) in sorted(vox):
        base = []
        for dx in (0, 1):
            for dy in (0, 1):
                for dz in (0, 1):
                    p = (x + dx, y + dy, z + dz)
                    if p not in idx:
                        idx[p] = len(verts) + 1
                        verts.append(p)
                    base.append(idx[p])
        c = {(a, b, e): idx[(x + a, y + b, z + e)]
             for a in (0, 1) for b in (0, 1) for e in (0, 1)}
        for nb, quad in (
            ((1, 0, 0), [(1, 0, 0), (1, 1, 0), (1, 1, 1), (1, 0, 1)]),
            ((-1, 0, 0), [(0, 0, 0), (0, 0, 1), (0, 1, 1), (0, 1, 0)]),
            ((0, 1, 0), [(0, 1, 0), (0, 1, 1), (1, 1, 1), (1, 1, 0)]),
            ((0, -1, 0), [(0, 0, 0), (1, 0, 0), (1, 0, 1), (0, 0, 1)]),
            ((0, 0, 1), [(0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1)]),
            ((0, 0, -1), [(0, 0, 0), (0, 1, 0), (1, 1, 0), (1, 0, 0)]),
        ):
            if (x + nb[0], y + nb[1], z + nb[2]) in vox:
                continue
            faces.append([c[q] for q in quad])
    for v in verts:
        lines.append("v %d %d %d" % v)
    for f in faces:
        lines.append("f " + " ".join(str(i) for i in f))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    build(sys.argv[1], sys.argv[2])
