"""Regenerate surfaces_table.py from the decompilation's own labels.

Run this, not a hand-written table. The point is that every semantic claim
about a cell traces back to a name in zeldaret/tmc rather than to something
inferred from colour -- and that a fresh checkout can rebuild it, with no
ROM asset anywhere in the chain. tiles.h is source, not ripped data.

    python3 tools/gen_surfaces.py /path/to/tmc-master
"""
import re
import sys
from pathlib import Path


def main():
    root = Path(sys.argv[1] if len(sys.argv) > 1 else "../tmc-master")
    tiles = root / "include" / "tiles.h"
    player = root / "include" / "player.h"
    if not tiles.exists():
        sys.exit(f"no {tiles} -- pass the path to a tmc checkout")
    th = tiles.read_text()
    ph = player.read_text() if player.exists() else ""

    act = {}
    for v, name in re.findall(
            r"ACT_TILE_\d+\s*=\s*(0x[0-9a-fA-F]+),\s*//[^\n]*?->\s*(SURFACE_\w+)",
            th):
        act[int(v, 16)] = name

    coll = {}
    for v, note in re.findall(
            r"COLLISION_DATA_\d+\s*=\s*(0x[0-9a-fA-F]+),\s*//\s*(FX_\w+)", th):
        coll[int(v, 16)] = note

    order = re.findall(r"^\s+(SURFACE_\w+)", ph, re.M)
    surf = {n: i for i, n in enumerate(dict.fromkeys(order))}

    out = Path(__file__).with_name("surfaces_table.py")
    with out.open("w") as f:
        f.write('"""Generated by gen_surfaces.py from the tmc decomp. '
                'Do not edit."""\n\n')
        f.write("ACT_SURFACE = {\n")
        for k in sorted(act):
            f.write("    0x%02x: %r,\n" % (k, act[k]))
        f.write("}\n\nCOLLISION_FX = {\n")
        for k in sorted(coll):
            f.write("    0x%02x: %r,\n" % (k, coll[k]))
        f.write("}\n\nSURFACE_ID = {\n")
        for n in surf:
            f.write("    %r: 0x%02x,\n" % (n, surf[n]))
        f.write("}\n")
    print(f"{out}: {len(act)} act->surface, {len(coll)} collision fx, "
          f"{len(surf)} surface names")


if __name__ == "__main__":
    main()
